#!/bin/sh

if [ "`id -u`" != "0" ]; then
    echo "autopilot needs to be run as:  sudo autopilot"
    exit 1
fi

echo "We're now going to create two disk images, create some files on one,"
echo "copy them to the other, and find out what metadata was preserved."
echo

set -ex

make
hdiutil eject /Volumes/Src || true
hdiutil eject /Volumes/Dst || true
rm -v Src.sparseimage || true
rm -v Dst.sparseimage || true
./bbouncer create-vol Src
./bbouncer create-vol Dst
./bbouncer create /Volumes/Src
./bbouncer copy -d /Volumes/Src /Volumes/Dst
